version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - npm install
      - npm install -D @tessellator/sveltekit-adapter-lambda
      - npm run build
    on-failure: ABORT
    artifacts:
      files:
        - '/*'
      name: iamgroot
  post_build:
    commands:
      - aws s3 cp ./build s3://iamgroot-bucket --recursive


